do hw
RetKinf/Spring-boot-intro pull request #12
Opened 2024-07-22 15:42 UTC by RetKinf

2024-07-23 09:48 UTC, Elena-Bruyako commented on src/main/java/com/example/config/OpenApiConfig.java
> +
```suggestion
```

2024-07-23 09:48 UTC, Elena-Bruyako commented on src/main/java/com/example/config/OpenApiConfig.java
> +                .components(new Components().addSecuritySchemes("BearerAuth",
Use constant for "BearerAuth"

2024-07-23 09:48 UTC, Elena-Bruyako commented on src/main/java/com/example/config/OpenApiConfig.java
> +    }
Why is this class was included in this PR?

2024-07-23 09:49 UTC, Elena-Bruyako commented on src/main/java/com/example/model/Book.java
> +    @ManyToMany(fetch = FetchType.LAZY)
```suggestion
    @ManyToMany
```

2024-07-23 09:52 UTC, Elena-Bruyako commented on src/main/java/com/example/controller/CategoryController.java
> +    }
Haven't find `public CategoryDto getCategoryById(Long id)`

2024-07-23 10:15 UTC, RetKinf commented on src/main/java/com/example/config/OpenApiConfig.java
> +    }
It was not mandatory to add JWT in the topic, but I decided that it would be better to include it

2024-07-23 10:29 UTC, RetKinf commented on src/main/java/com/example/controller/CategoryController.java
> +    }
![image](https://github.com/user-attachments/assets/37d68556-1f7f-418f-8f10-8851fd67189f)

I focused on these methods for User and didn't notice that it was also necessary to add "public CategoryDto getCategoryById(Long id)".

2024-07-24 10:44 UTC, MentorMateAcademy requested changes

2024-07-24 10:44 UTC, MentorMateAcademy commented on src/main/java/com/example/config/OpenApiConfig.java
> +                                .bearerFormat("JWT")))
can save to constants too

2024-07-24 10:44 UTC, MentorMateAcademy commented on src/main/java/com/example/dto/category/CreateCategoryRequestDto.java
> +    private String description;
you can validate description too

2024-07-24 11:08 UTC, RetKinf commented on src/main/java/com/example/dto/category/CreateCategoryRequestDto.java
> +    private String description;
![image](https://github.com/user-attachments/assets/9ccbb2c1-0a86-4fdf-bc84-70cbca1f75b3)

How can I validate the description if there are no conditions specified for it in the assignment?

2024-07-25 09:28 UTC, okuzan commented on src/main/java/com/example/dto/category/CreateCategoryRequestDto.java
> +    private String description;
Mentor meant max Size, for example. Even if description is optional, still makes sense to have some limit

2024-07-25 09:29 UTC, okuzan approved these changes

2024-07-25 09:29 UTC, okuzan commented on src/main/java/com/example/model/Category.java
> +@SQLRestriction("is_deleted=false")
```suggestion
@SQLDelete(sql = "UPDATE categories SET is_deleted = TRUE WHERE id = ?")
@SQLRestriction("is_deleted = FALSE")
```

2024-07-25 11:59 UTC, merged